site_name: My Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true