name: mkdocs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "**.md"
      - .github/workflows/docs.yml
      - mkdocs.yml

env:
  actor: "41898282+github-actions[bot]"
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: git config
        run: |
          git config --local user.email "${actor}@users.noreply.github.com"
          git config --local user.name "$actor"
      - run: pip install --upgrade pip
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force
